apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml
- service-mesh-namespace.yaml
- service-mesh-operatorgroup.yaml
- service-mesh-subscription.yaml
- dsci.yaml
- datasciencecluster.yaml
- mlflow.yaml
