apiVersion: v1
kind: ServiceAccount
metadata:
  name: acp-image-puller
  namespace: acp-image-puller
  labels:
    app.kubernetes.io/part-of: acp-image-puller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acp-image-puller
  labels:
    app.kubernetes.io/part-of: acp-image-puller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acp-image-puller
  labels:
    app.kubernetes.io/part-of: acp-image-puller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acp-image-puller
subjects:
  - kind: ServiceAccount
    name: acp-image-puller
    namespace: acp-image-puller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acp-image-puller
  namespace: acp-image-puller
  labels:
    app.kubernetes.io/part-of: acp-image-puller
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acp-image-puller
  namespace: acp-image-puller
  labels:
    app.kubernetes.io/part-of: acp-image-puller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acp-image-puller
subjects:
  - kind: ServiceAccount
    name: acp-image-puller
    namespace: acp-image-puller
