// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 97773951f427a0271532ec5ed2e18c6441b246989b0aebbe755b544b47e2e702
// Generated: 2026-04-18T21:11:11Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type CredentialAPI struct {
	client *Client
}

func (c *Client) Credentials() *CredentialAPI {
	return &CredentialAPI{client: c}
}
func (a *CredentialAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/projects/{id}/credentials")
}

func (a *CredentialAPI) Create(ctx context.Context, resource *types.Credential) (*types.Credential, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal credential: %w", err)
	}
	var result types.Credential
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) Get(ctx context.Context, id string) (*types.Credential, error) {
	var result types.Credential
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) List(ctx context.Context, opts *types.ListOptions) (*types.CredentialList, error) {
	var result types.CredentialList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *CredentialAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Credential, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Credential
	if err := a.client.do(ctx, http.MethodPatch, a.basePath()+"/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *CredentialAPI) GetToken(ctx context.Context, id string) (*types.CredentialTokenResponse, error) {
	var result types.CredentialTokenResponse
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id)+"/token", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Credential] {
	return NewIterator(func(page int) (*types.CredentialList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
